### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by onkoe** [MCsniperPY/MCsniperPY#1]
The developer of 3Snipe is currently implementing native proxy support. If you could do the same, I would be super happy, as this program has always worked much better than 3Snipe for my purposes. Thanks!~

**Comment by onkoe** [comment]
Also, please label this as a suggestion. I forgot :)

**Comment by oTeun** [comment]
proxies are slow tho, without proxies is way better tbh

**Comment by onkoe** [comment]
That's not wrong, but if you're using multiple instances of the software at once, all of your requests will be denied, meaning a VPN is required for at least one instance. Also, it depends on the proxy. I have one on my provider that is quite close to me. Anyways, I don't think anyone would really complain about it if they have a higher chance to snipe a name :)

**Comment by Kqzz** [comment]
Thanks for submitting this suggestion, I will keep this in mind. Are you in the discord? I'm much more active about what I'm doing and things like that there.

**Comment by onkoe** [comment]
Yes; I am barrett#0001. You can clearly see me reacting on most announcements to flex my Discord Nitro. :) Anyways, I will watch for any news surrounding this topic.

**Comment by Kqzz** [comment]
alright, awesome.

**Comment by Kqzz** [comment]
I don't think I'll ever be adding this tbh.
