### ISSUE TITLE
name change check

### ISSUE THREAD

**Issue by sinister** [MCsniperPY/MCsniperPY#13]
currently as far as I can see, your code does not check if the account has changed its name in the last 30 days

this might be a worthwhile addition as some sfa sites resell accounts so people might have accounts that others have already sniped names onto, you can see an example of how to do this [here](https://github.com/sinister/Minecraft-SFA-scripts/blob/master/sfa_checker.py)

**Comment by sinister** [comment]
my advice would be to add a startup argument or something to let people check their accounts for name changes since this feature only needs to be done once (unless they add new accounts), not every single time they wise to snipe a name

**Comment by Kqzz** [comment]
This has been implemented by Tenscape and Duff with the new API. Sorry for the long time to get back.
