### ISSUE TITLE
Code Readability

### ISSUE THREAD

**Issue by aquild** [MCsniperPY/MCsniperPY#15]
*DISCLAIMER: While this isn't a problem with MCsniperPY's actual functionality, I feel that it's important to it's development.*

MCsniperPY's code is ugly. It's very difficult to read and understand due largely to ambiguous naming and it's largely additive nature. Because it's so hard to understand, it can be difficult for someone not acquainted with the project to contribute. This is probably why MCsniperPY, despite having 15+ forks still only has 3 contributors.

I suggest that MCsniperPY's code be refactored so as to be more expressive and easily modified. One such change could be splitting the codebase into multiple files and making names more consistent.

**Comment by actuallydoc** [comment]
i agree with that one

**Comment by Kqzz** [comment]
I also agree with this. Honestly, the only reason I'm not doing this is because I don't really want to. I may recode the sniper in golang or another language if I feel like it and in that case I'd try to make the code much cleaner.
