### ISSUE TITLE
Problem with licensing

### ISSUE THREAD

**Issue by Henry0w** [MCsniperPY/MCsniperPY#17]
The GNU GPL v3 only requires people to provide source code with actual copies of the program. This means that if someone hosts this on the internet, as long they don't provide a download for the program, they **do not** need to provide source code. I highly recommend switching to the AGPL v3 in order to fix this.

**Comment by Kqzz** [comment]
Thanks for bringing this to my attention. Honestly I'm not that worried about this but I'll look into it.

**Comment by Kqzz** [comment]
The sniper is done, so I'm closing this with no further action. Thanks for bringing this to my attention though 😄
