### ISSUE TITLE
A LOT of 429 errors

### ISSUE THREAD

**Issue by snuckdev** [MCsniperPY/MCsniperPY#20]
Hey, I was using this sniper in the day before yesterday and it was working normal. But I tried today to snipe 4 names. My account has security questions, but I don't think this is the problem.
I tried to snipe and only 3 requests were sent successfuly, but got 403s. Here's the print of my snipe.
I already changed the snipe requests amount to everythink: tried with 8 requests, 5 requests, 3 requests and 40 requests just for testing. And in all of the cases I got 429s.
https://imgur.com/cMsy3FI

**Comment by Henry0w** [comment]
That's normal. If your only using 1 account you should get rate limited to 3 requests per name you're sniping.

**Comment by Kqzz** [comment]
Yeah, this is sadly the new norm. You can lower `snipe_reqs` in config.txt which will make the sniper attempt the name less but sometimes will produce fewer 429s.
