### ISSUE TITLE
Sniper Shuts off last second

### ISSUE THREAD

**Issue by BazookaB3n** [MCsniperPY/MCsniperPY#34]
At about a minute left until the name drops, the sniper says an error code and immediately shuts off afterwards.

**Comment by Kqzz** [comment]
I can't do much with this information. Without the error code, operating system, etc.. I can't fix this bug. Please re-open an issue with that information. 

If you're running into a problem with it just "shutting off" then run it in cmd as instructed in the `#usage` channel so you'll be able to see the full error code.
