### ISSUE TITLE
recode installation results with no module installed

### ISSUE THREAD

**Issue by overestimate** [MCsniperPY/MCsniperPY#38]
results with the following line a few times in the output, possibly related
`file mcsniperpy.py (for module mcsniperpy) not found`

**Comment by overestimate** [comment]
uhh this shouldnt have submitted

**Comment by Kqzz** [comment]
can you provide more information? I'm not sure I understand.

**Comment by overestimate** [comment]
okay, for whatever reason it works now

**Comment by Kqzz** [comment]
:+1:
