### ISSUE TITLE
Config not being made on init

### ISSUE THREAD

**Issue by Kqzz** [MCsniperPY/MCsniperPY#41]
[error] type: KeyError
[error] message: 'sniper'

Error probably caused by config.py file

**Comment by overestimate** [comment]
#42

**Comment by Kqzz** [comment]
Im pretty sure I fixed this, but it has yet to be tested on anything but xubuntu 20.04.

**Comment by Kqzz** [comment]
Gonna close. I can reopen it it doesn’t work once tested.
