### ISSUE TITLE
the cmd prompt

### ISSUE THREAD

**Issue by poggerschsa** [MCsniperPY/MCsniperPY#43]
it retuns the error PermissionError: [Errno 13] Permission denied: 'accounts.txt'

**Comment by Kqzz** [comment]
What operating system are you on? and what usage did you follow?

**Comment by poggerschsa** [comment]
i followed it exactly and i use windows 10

**Comment by Kqzz** [comment]
what guide?

**Comment by Kqzz** [comment]
Without more information I can't fix this. Please open another issue if you have more info.
