### ISSUE TITLE
add custom announce to recode

### ISSUE THREAD

**Issue by Kqzz** [MCsniperPY/MCsniperPY#52]
add custom announce api to the rewrite. oh and rewrite the custom announce api :neutral_face:

**Comment by Kqzz** [comment]
Unless I'm stupid I already added this

**Comment by office** [comment]
i think you are stupid

**Comment by oTeun** [comment]
> i think you are stupid

What he said

**Comment by Kqzz** [comment]
Well yes, but I wasn't sure if it works.
