### ISSUE TITLE
Microsoft Authentication Support

### ISSUE THREAD

**Issue by hashblen** [MCsniperPY/MCsniperPY#54]
Hello
can someone please add the microsoft accounts, because new bought accounts are now microsoft
thanks

**Comment by Kqzz** [comment]
This is something that will eventually be added but is not a priority at all. A bug-less recode is the main priority at the moment.

**Comment by Kqzz** [comment]
At this point I think I'm going to add _manual bearer_ support which should allow for microsoft accounts.

**Comment by Kqzz** [comment]
Never happening, sadly. I'm planning on making another sniper, which will be free & open source.
