### ISSUE TITLE
Ugly Title

### ISSUE THREAD

**Issue by Kqzz** [MCsniperPY/MCsniperPY#55]
The title for when you start MCsniperPY is kind ugly imo. Needs to have more color in it.
![image](https://user-images.githubusercontent.com/48300938/111075037-6b121f80-84bc-11eb-8ff8-9a44466daf85.png)

**Comment by overestimate** [comment]
You can skip a character with `"\033[P1C"` (sourced from https://sites.google.com/a/dee.ufcg.edu.br/rrbrandt/en/docs/ansi/cursor)

**Comment by Kqzz** [comment]
oooh cool, thanks. I'll check that out.
