### ISSUE TITLE
Issue when starting sniper

### ISSUE THREAD

**Issue by waifsu** [MCsniperPY/MCsniperPY#58]
When starting py sniper with py snipe.py and error occurs with
File "snipe.py", line 41
    logging.info(f"{Fore.WHITE}[{Fore.BLUE}info{Fore.WHITE}] {Fore.RESET}{message}")
                                                                                                                                    ^
                                                                                                                                  
SyntaxError: invalid syntax

**Comment by Kqzz** [comment]
don't run it with python 2.

**Comment by Kqzz** [comment]
This is not a problem with the sniper, which is why I closed this issue.
