### ISSUE TITLE
add heroku support

### ISSUE THREAD

**Issue by snuckdev** [MCsniperPY/MCsniperPY#59]
Could you add Heroku support? Like a big purple button that leads to heroku auto deploy.

**Comment by Kqzz** [comment]
Heroku is used for hosting web apps, not scripts. Also, if you were to do it multiple times your IP would change, which _could_ lead to a locked account. While I don't think this is something I want to do, I will consider adding support for deploying on a VM through google cloud.

**Comment by snuckdev** [comment]
ok thanks
