### ISSUE TITLE
Bot is failing to time a snipe

### ISSUE THREAD

**Issue by Commotive** [MCsniperPY/MCsniperPY#70]
I was trying to snipe the username Ballroom for later tonight but when I out in the name and the 1000 for delay it failed to time snipe and crashed

**Comment by freshgesh** [comment]
Same happened to me! I tried sniping 8ww with a 715 delay, and it said the saim thing! I eaven tried it with a 400 delay but it still dosent work! Please help us!

**Comment by Kqzz** [comment]
This will happen on any name, any time namemc is using Cloudflare protection on their website. They recently enabled it, disabled it, and then reenabled it. I'm working on a proprietary droptime server that I'll run which will be able to give droptimes even when namemc is down. I should have it out in a few days.

**Comment by thecatlovva** [comment]
Sweet! Thank you so much

**Comment by Kqzz** [comment]
Fixed on the recode. Check the #announcements channel in discord for a fix. tl;dr download recode (https://docs.mcsniperpy.com) and change timing_system to `teun` in config.ini.
