### ISSUE TITLE
weird error that idk how to fix

### ISSUE THREAD

**Issue by Vortecked** [MCsniperPY/MCsniperPY#84]
i tried multiple things including reinstalling python and the sniper, but get this error message: 
![image](https://user-images.githubusercontent.com/71997442/125001098-bc639300-e006-11eb-82b9-e968c0f1a27d.png)

**Comment by overestimate** [comment]
Can you upload you config files to this issue? Something's amiss with the timing selection, usually a result of user error.

**Comment by Kqzz** [comment]
This is caused by the coolkidmacho api, i can look into providing a better error message later.

**Comment by overestimate** [comment]
@Kqzz Could you rename this to `CKM API failing to fetch droptime`? Current issue name isn't very descriptive. Thanks.

**Comment by coolkidmacho** [comment]
If needed I can add the error message.

**Comment by Kqzz** [comment]
That'd definitely be helpful. No reason to return html in an API. You definitely want to return a logical error message across all endpoints, and not just let the code error and give some html.

**Comment by coolkidmacho** [comment]
Sounds good, the error is commonly caused by names that are not cached. Will be fixed within 24 hours.

**Comment by tenscape** [comment]
Coolkidmacho api SUCKS
rip teun api
peet private api on top 😼

**Comment by wwhtrbbtt** [comment]
> Coolkidmacho api SUCKS
> rip teun api
> peet private api on top 😼

Some can add my API as a backup or something

**Comment by coolkidmacho** [comment]
> Sounds good, the error is commonly caused by names that are not cached. Will be fixed within 24 hours.

Fixed.

**Comment by wwhtrbbtt** [comment]
> > Sounds good, the error is commonly caused by names that are not cached. Will be fixed within 24 hours.
> 
> Fixed.

Non-cached names still seem to return a HTML error page (http://api.coolkidmacho.com/droptime/123). I think it would be better, if you could return json data with the error message

**Comment by Kqzz** [comment]
Definitely, @coolkidmacho you should implement this.

**Comment by coolkidmacho** [comment]
> Definitely, @coolkidmacho you should implement this.

Done

**Comment by tenscape** [comment]
> > Definitely, @coolkidmacho you should implement this.
> 
> Done

Takes 3 days to do that . ShitAPI
peet api on top
rip teun api 🕊

**Comment by Itsmeerez** [comment]
> > Sounds good, the error is commonly caused by names that are not cached. Will be fixed within 24 hours.
> 
> 
> 
> Fixed.

Thx so much.

**Comment by overestimate** [comment]
Close this when you get a chance, @Kqzz
