### ISSUE TITLE
auth

### ISSUE THREAD

**Issue by joacogp191** [MCsniperPY/MCsniperPY#86]
I downloaded everything all worked correctly until when i set the offset it says failed to auth .......@icloud.com. (dots are to hide my acc name

**Comment by Jam-Github** [comment]
Please send the full error, and I'll be happy to look into it for you.

**Comment by joacogp191** [comment]
Thanks for trying to help but someone on discord already helped me they
told me it didnt work for microsoft accounts

**Comment by Jam-Github** [comment]
Alright :) Glad to hear you got it sorted.

**Comment by Kqzz** [comment]
Microsoft authentication is in my new sniper, creatively named MCsniperGO... There is no documentation for that sniper yet due to it not being finished yet, but i'm guessing it'll be released in the next week or two officially, and will replace MCsniperPY.
