### ISSUE TITLE
Errors with every timing api

### ISSUE THREAD

**Issue by Corrupt10n404** [MCsniperPY/MCsniperPY#89]
Regardless of the timing_system parameter in config.ini (teun, ckm, kqzz_api, namemc), there is an error for every name I try to snipe. As soon as I enter the name and delay, I get one of these errors in order of
teun
ckm
kqzz_api
namemc
![namemc](https://user-images.githubusercontent.com/52146696/128559281-2459879d-8598-488c-8f36-a096335e3d25.png)
![kqzz_api](https://user-images.githubusercontent.com/52146696/128559284-02ab9741-0f5b-49f4-b974-ad7477069a39.png)
![ckm](https://user-images.githubusercontent.com/52146696/128559286-a90d4cad-f1c4-41b3-b4eb-166bf646ec48.png)
![teun](https://user-images.githubusercontent.com/52146696/128559287-421f5feb-abd1-45a2-9860-9741882883ce.png)

I'm not sure if this is a mistake on my part, or if all of these timing systems are just not working. I'd appreciate a solution to the issue either way :)

**Comment by tenscape** [comment]
femboy api
just saying

**Comment by Kqzz** [comment]
In my new sniper I'm going to be implementing a new droptime API that is much more stable.
